services:
  setr:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: setr-container
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Use all available GPUs
    volumes:
      - .:/app  # Mount the current directory into the container
    restart: always
    tty: true
    runtime: nvidia
